// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmf3UP-eFV7UonDaGf7V5NG_jDNNHusdY',
    appId: '1:79816309828:web:bfc442f2af5b5cf4ce1011',
    messagingSenderId: '79816309828',
    projectId: 'themovie-7b1ee',
    authDomain: 'themovie-7b1ee.firebaseapp.com',
    storageBucket: 'themovie-7b1ee.firebasestorage.app',
    measurementId: 'G-P9HXMVBD9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpYOdLZx4R8lsukMgmWAWrRBkZLqrl-4A',
    appId: '1:79816309828:android:74e52344132d8082ce1011',
    messagingSenderId: '79816309828',
    projectId: 'themovie-7b1ee',
    storageBucket: 'themovie-7b1ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLehKQUYypBpxYQwxXBECRxweBGsARfZ4',
    appId: '1:79816309828:ios:6fdff7e7d4d35feace1011',
    messagingSenderId: '79816309828',
    projectId: 'themovie-7b1ee',
    storageBucket: 'themovie-7b1ee.firebasestorage.app',
    iosBundleId: 'com.example.themovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLehKQUYypBpxYQwxXBECRxweBGsARfZ4',
    appId: '1:79816309828:ios:6fdff7e7d4d35feace1011',
    messagingSenderId: '79816309828',
    projectId: 'themovie-7b1ee',
    storageBucket: 'themovie-7b1ee.firebasestorage.app',
    iosBundleId: 'com.example.themovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmf3UP-eFV7UonDaGf7V5NG_jDNNHusdY',
    appId: '1:79816309828:web:2b1be46e48dd0f17ce1011',
    messagingSenderId: '79816309828',
    projectId: 'themovie-7b1ee',
    authDomain: 'themovie-7b1ee.firebaseapp.com',
    storageBucket: 'themovie-7b1ee.firebasestorage.app',
    measurementId: 'G-W1461YDQV2',
  );
}
